[package]
name = "counter"
version = "1.0.0"
authors = []

[addresses]
counter_addr='7d30c480ffec596ecc7ac1bb217b5ef60c475ca20cdaeb3bf657f93972b02579'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
